spring:
  datasource:
    url: jdbc:h2:~/Documents/grupogfiapdatabase;DB_CLOSE_ON_EXIT=FALSE
    username: grupog
    password: grupog
  h2:
    console.enabled: true

tesseract:
  lang: por
  trained:
    path: src/main/resources/tessdata
async:
  threadpool:
    maxsize: 20
    queuesize: 100